CREATE TABLE IF NOT EXISTS suppliers_table (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    document_cnpj VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);